  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      ports:
        - "8020:8020"
      environment:
        - DATABASE_URL=postgres://postgres:postgres@db/postgres
      depends_on:
        - db
