# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_Administrador', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=12)),
                ('contrasena', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField()),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CambioInventario',
            fields=[
                ('id_CambioInventario', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(default=1)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=30)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeAcopio',
            fields=[
                ('id_Centro', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreUPC', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('provincia', models.CharField(max_length=30)),
                ('canton', models.CharField(max_length=30)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_Habilidad', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreHabilidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadHelpMapper',
            fields=[
                ('id_HabilidadHelpMapper', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('id_Habilidad', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='HelpMapper',
            fields=[
                ('id_HelpMapper', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=12)),
                ('contrasena', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('estado', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipoSangre', models.CharField(max_length=5)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.CharField(default='-', max_length=16, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('id_Categoria', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Categoria')),
                ('id_Centro', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.CentroDeAcopio')),
            ],
        ),
        migrations.AddField(
            model_name='habilidadhelpmapper',
            name='id_HelpMapper',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.HelpMapper'),
        ),
        migrations.AddField(
            model_name='cambioinventario',
            name='id_producto',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Producto'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_Centro',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.CentroDeAcopio'),
        ),
    ]
