# Generated by Django 3.1 on 2020-08-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre_usuario', models.CharField(default='-', max_length=12, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(default='-', max_length=15)),
                ('correo', models.EmailField(default='-', max_length=254)),
                ('tipo', models.IntegerField(default=1)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(default='-', max_length=30)),
                ('unidad', models.CharField(default='-', max_length=20)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_upc', models.CharField(default='-', max_length=30)),
                ('direccion', models.CharField(default='-', max_length=100)),
                ('latitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('provincia', models.CharField(default='-', max_length=30)),
                ('canton', models.CharField(default='-', max_length=30)),
                ('estado', models.IntegerField(default=1)),
                ('almacenamiento_agua', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('almacenamiento_ropa', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('almacenamiento_comida', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('usuario_admin', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='HelpMapper',
            fields=[
                ('nombre', models.CharField(default='-', max_length=100)),
                ('apellido', models.CharField(default='-', max_length=100)),
                ('nombre_usuario', models.CharField(default='-', max_length=18, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(default='-', max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=5)),
                ('cedula', models.CharField(default='-', max_length=10)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=5)),
                ('telefono', models.CharField(default='-', max_length=10)),
                ('correo', models.EmailField(max_length=100)),
                ('habilidad', models.CharField(choices=[('Primeros Auxilios', 'Primeros Auxilios'), ('Culinarias', 'Culinarias'), ('Trabajo de Campo', 'Trabajo de Campo')], default='Primeros Auxilios', max_length=30)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(default='-', max_length=30)),
                ('estado', models.IntegerField(default=1)),
                ('id_categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helpmapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ExistenciaInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('id_centro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helpmapp.centrodeacopio')),
                ('id_producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helpmapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CambioInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=1)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_centro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helpmapp.centrodeacopio')),
                ('id_producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helpmapp.producto')),
            ],
        ),
    ]
