# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpmapp', '0003_auto_20170730_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidad',
            old_name='nombre_habilidad',
            new_name='nombreHabilidad',
        ),
        migrations.RenameField(
            model_name='helpmapper',
            old_name='nombre_usuario',
            new_name='nombreUsuario',
        ),
        migrations.RenameField(
            model_name='helpmapper',
            old_name='tipo_sangre',
            new_name='tipoSangre',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='idAdministrador',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='idCentro',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='centrodeacopio',
            name='idCentro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCentro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_Administrador',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_Centro',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.CentroDeAcopio'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_Categoria',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='centrodeacopio',
            name='id_Centro',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Categoria',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Centro',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.CentroDeAcopio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Producto',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cambioinventario',
            name='id_CambioInventario',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cambioinventario',
            name='id_producto',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Producto'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='id_Habilidad',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habilidadhelpmapper',
            name='id_HabilidadHelpMapper',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habilidadhelpmapper',
            name='id_Hablidad',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.Habilidad'),
        ),
        migrations.AlterField(
            model_name='habilidadhelpmapper',
            name='id_HelpMapper',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='helpmapp.HelpMapper'),
        ),
        migrations.AlterField(
            model_name='helpmapper',
            name='id_HelpMapper',
            field=models.CharField(default=b'', max_length=16, primary_key=True, serialize=False),
        ),
    ]
