# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpmapp', '0004_auto_20170731_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidadhelpmapper',
            old_name='id_Hablidad',
            new_name='id_Habilidad',
        ),
    ]
